swagger: '2.0'
info:
  title: 'QLNhanSu API'
  description: 'API documentation for QLNhanSu system'
  version: '1.0.0'
  contact:
    email: 'support@qlnhansu.com'
  license:
    name: 'MIT'
    url: 'https://opensource.org/licenses/MIT'

host: 'localhost:3000'
basePath: '/api'
schemes:
  - http
  - https

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Authorization header using the Bearer scheme. Example: "Bearer {token}"'

paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: 'User login'
      description: 'Authenticate user and return JWT token'
      operationId: 'login'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'User credentials'
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: 'Successful login'
          schema:
            type: object
            properties:
              token:
                type: string
        '401':
          description: 'Invalid credentials'
        '500':
          description: 'Server error'

  /users:
    get:
      tags:
        - users
      summary: 'Get all users'
      description: 'Returns a list of users'
      operationId: 'getUsers'
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        '200':
          description: 'Successful operation'
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '401':
          description: 'Unauthorized'
        '500':
          description: 'Server error'

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      role:
        type: string
      department:
        type: string
      position:
        type: string
      status:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time 